// =============================================================================
// Auto-generated seed data from Excel workbook
// Used for demo/preview mode when Supabase is unavailable
// =============================================================================

import type { Branch, Classification, WhatIf, EmployeeRow, EquipmentRow } from "@/lib/formulas/types";

export const SEED_BRANCHES: Branch[] = [
  { id: "branch-newroch", name: "New Rochelle", state: "NY", display_label: "NEW ROCHELLE NY BRANCH", wc_rate: 0.0617, pr_rate: 0.1226, medical_per_hr: 0, overhead_per_hr: 48.06, storm_bonus_per_8h: 0, sort_order: 1 },
  { id: "branch-hawthorne", name: "Hawthorne", state: "NY", display_label: "HAWTHORNE NY BRANCH", wc_rate: 0.0617, pr_rate: 0.1544, medical_per_hr: 0, overhead_per_hr: 43.8, storm_bonus_per_8h: 0, sort_order: 2 },
  { id: "branch-stamford", name: "Stamford", state: "CT", display_label: "STAMFORD CONNECTICUT BRANCH", wc_rate: 0.0526, pr_rate: 0.1712, medical_per_hr: 0, overhead_per_hr: 41.13, storm_bonus_per_8h: 0, sort_order: 3 },
  { id: "branch-haledon", name: "North Haledon", state: "NJ", display_label: "NORTH HALEDON NJ BRANCH", wc_rate: 0.1053, pr_rate: 0.2131, medical_per_hr: 0, overhead_per_hr: 49.66, storm_bonus_per_8h: 0, sort_order: 4 },
];

export const SEED_CLASSIFICATIONS: Classification[] = [
  { id: "cls-foreman", label: "Foreman", emp_class: "Foreman", reg_wage: 50.29, reg_supp: 29.13, ot_wage: 75.435, ot_supp: 29.13, description: "Westchester Heavy & Highway GR III", sort_order: 1 },
  { id: "cls-climber", label: "Climber", emp_class: "Climber", reg_wage: 50.29, reg_supp: 29.13, ot_wage: 75.435, ot_supp: 29.13, description: "Westchester Heavy & Highway GR III", sort_order: 2 },
  { id: "cls-groundman", label: "Groundman", emp_class: "Groundperson", reg_wage: 49.56, reg_supp: 29.13, ot_wage: 74.34, ot_supp: 29.13, description: "Westchester Heavy & Highway GR V", sort_order: 3 },
  { id: "cls-other1", label: "Other-1", emp_class: "Spray Tech", reg_wage: 0, reg_supp: 0, ot_wage: 0, ot_supp: 0, description: "PHC Spray Tech (non-certified)", sort_order: 4 },
  { id: "cls-other2", label: "Other-2", emp_class: "Lawn Tech", reg_wage: 0, reg_supp: 0, ot_wage: 0, ot_supp: 0, description: "Lawn Tech (non-certified)", sort_order: 5 },
];

export const SEED_WHAT_IF: WhatIf = {
  profit_pct: 0.25,
  contrib_margin_pct: 1.0,
  fuel_per_gal: 5.50,
  emergency_mult: 2.0,
};

export const SEED_EMPLOYEES: EmployeeRow[] = [
  { id: "emp-0", branch_id: "branch-hawthorne", emp_no: "000073", classification: "Foreman", last_name: "ALCANTAR", first_name: "CARLOS", pay_per_hr: 43.0, supplemental_per_hr: 5.71, active: true },
  { id: "emp-1", branch_id: "branch-hawthorne", emp_no: "000070", classification: "Climber", last_name: "ALCANTAR", first_name: "JOSE", pay_per_hr: 20.0, supplemental_per_hr: 2.89, active: true },
  { id: "emp-2", branch_id: "branch-hawthorne", emp_no: "001356", classification: "Lawn Tech", last_name: "ALCANTAR", first_name: "EFREN", pay_per_hr: 22.0, supplemental_per_hr: 1.47, active: true },
  { id: "emp-3", branch_id: "branch-hawthorne", emp_no: "001542", classification: "Climber", last_name: "ALMADA ZORRILLA", first_name: "MARCOS", pay_per_hr: 35.0, supplemental_per_hr: 2.33, active: true },
  { id: "emp-4", branch_id: "branch-hawthorne", emp_no: "000077", classification: "Foreman", last_name: "LICEA", first_name: "ANTONIO", pay_per_hr: 29.0, supplemental_per_hr: 2.64, active: true },
  { id: "emp-5", branch_id: "branch-hawthorne", emp_no: "001553", classification: "Climber", last_name: "ARAGON MORENO", first_name: "VALENTIN", pay_per_hr: 37.0, supplemental_per_hr: 2.47, active: true },
  { id: "emp-6", branch_id: "branch-hawthorne", emp_no: "001297", classification: "Spray Tech", last_name: "CASTILLO SOLIS", first_name: "JAVIER", pay_per_hr: 31.0, supplemental_per_hr: 2.14, active: true },
  { id: "emp-7", branch_id: "branch-hawthorne", emp_no: "000110", classification: "Lawn Tech", last_name: "ANDREWS", first_name: "KEVIN", pay_per_hr: 39.0, supplemental_per_hr: 5.27, active: true },
  { id: "emp-8", branch_id: "branch-hawthorne", emp_no: "000098", classification: "Climber", last_name: "VERA", first_name: "ROQUE", pay_per_hr: 25.0, supplemental_per_hr: 2.39, active: true },
  { id: "emp-9", branch_id: "branch-hawthorne", emp_no: "001573", classification: "Spray Tech", last_name: "CASTILLO", first_name: "JAVIER (JAVIE)", pay_per_hr: 18.0, supplemental_per_hr: 1.2, active: true },
  { id: "emp-10", branch_id: "branch-hawthorne", emp_no: "001268", classification: "Groundperson", last_name: "ESCOTO JR", first_name: "OSIRIS", pay_per_hr: 17.5, supplemental_per_hr: 3.72, active: true },
  { id: "emp-11", branch_id: "branch-hawthorne", emp_no: "000102", classification: "Groundperson", last_name: "GOMEZ", first_name: "MARTIN", pay_per_hr: 21.0, supplemental_per_hr: 1.94, active: true },
  { id: "emp-12", branch_id: "branch-hawthorne", emp_no: "001520", classification: "Climber", last_name: "LOPEZ CARMONA", first_name: "SILVESTRE", pay_per_hr: 37.0, supplemental_per_hr: 2.29, active: true },
  { id: "emp-13", branch_id: "branch-hawthorne", emp_no: "001375", classification: "Climber", last_name: "MONGES", first_name: "LUIS", pay_per_hr: 23.0, supplemental_per_hr: 1.76, active: true },
  { id: "emp-14", branch_id: "branch-newroch", emp_no: "001298", classification: "Climber", last_name: "CUEVAS", first_name: "JOSE", pay_per_hr: 29.0, supplemental_per_hr: 2.32, active: true },
  { id: "emp-15", branch_id: "branch-newroch", emp_no: "000056", classification: "Foreman", last_name: "FLORES", first_name: "ALEJANDRO", pay_per_hr: 37.0, supplemental_per_hr: 4.83, active: true },
  { id: "emp-16", branch_id: "branch-newroch", emp_no: "001362", classification: "Climber", last_name: "ROSA", first_name: "ALEX", pay_per_hr: 32.0, supplemental_per_hr: 3.04, active: true },
  { id: "emp-17", branch_id: "branch-newroch", emp_no: "000100", classification: "Climber", last_name: "TORRES", first_name: "JOSE", pay_per_hr: 32.0, supplemental_per_hr: 1.81, active: true },
  { id: "emp-18", branch_id: "branch-newroch", emp_no: "000051", classification: "Operations Manager", last_name: "SOLORIO BEJINES", first_name: "ANTONIO", pay_per_hr: 60.1, supplemental_per_hr: 11.93, active: true },
  { id: "emp-19", branch_id: "branch-newroch", emp_no: "001378", classification: "Groundperson", last_name: "GALDAMEZ", first_name: "RICARDO JAVIER", pay_per_hr: 24.0, supplemental_per_hr: 1.6, active: true },
  { id: "emp-20", branch_id: "branch-newroch", emp_no: "000059", classification: "Groundperson", last_name: "OLIVEROS", first_name: "JOSE", pay_per_hr: 17.0, supplemental_per_hr: 1.89, active: true },
  { id: "emp-21", branch_id: "branch-newroch", emp_no: "000054", classification: "Groundperson", last_name: "BARAJAS", first_name: "ANTONIO", pay_per_hr: 28.0, supplemental_per_hr: 4.09, active: true },
  { id: "emp-22", branch_id: "branch-newroch", emp_no: "001591", classification: "Foreman", last_name: "MEZA CASTRO", first_name: "JESUS", pay_per_hr: 36.0, supplemental_per_hr: 2.4, active: true },
  { id: "emp-23", branch_id: "branch-newroch", emp_no: "001458", classification: "Climber", last_name: "SUY", first_name: "ELMAR", pay_per_hr: 32.0, supplemental_per_hr: 1.77, active: true },
  { id: "emp-24", branch_id: "branch-newroch", emp_no: "000053", classification: "Foreman", last_name: "BARAJAS", first_name: "RAUL", pay_per_hr: 35.0, supplemental_per_hr: 4.73, active: true },
  { id: "emp-25", branch_id: "branch-newroch", emp_no: "001338", classification: "Climber", last_name: "TELLES", first_name: "GUSTAVO", pay_per_hr: 31.0, supplemental_per_hr: 2.76, active: true },
  { id: "emp-26", branch_id: "branch-newroch", emp_no: "001225", classification: "Lawn Tech", last_name: "CUEVAS", first_name: "LUIS", pay_per_hr: 25.0, supplemental_per_hr: 2.17, active: true },
  { id: "emp-27", branch_id: "branch-newroch", emp_no: "000108", classification: "Foreman", last_name: "ROSA", first_name: "HUGO", pay_per_hr: 37.0, supplemental_per_hr: 3.19, active: true },
  { id: "emp-28", branch_id: "branch-newroch", emp_no: "000064", classification: "Climber", last_name: "GALVEZ", first_name: "JORGE", pay_per_hr: 35.0, supplemental_per_hr: 3.89, active: true },
  { id: "emp-29", branch_id: "branch-newroch", emp_no: "000177", classification: "Groundperson", last_name: "VALDOVINOS", first_name: "RICARDO", pay_per_hr: 29.0, supplemental_per_hr: 2.04, active: true },
  { id: "emp-30", branch_id: "branch-newroch", emp_no: "000058", classification: "Spray Tech", last_name: "MARTINEZ", first_name: "CESAR", pay_per_hr: 28.0, supplemental_per_hr: 2.56, active: true },
  { id: "emp-31", branch_id: "branch-newroch", emp_no: "001559", classification: "Spray Tech", last_name: "DELGADO", first_name: "ESTEBAN", pay_per_hr: 20.0, supplemental_per_hr: 1.33, active: true },
  { id: "emp-32", branch_id: "branch-newroch", emp_no: "000097", classification: "Groundperson", last_name: "ROSA", first_name: "MIGUEL", pay_per_hr: 26.0, supplemental_per_hr: 2.35, active: true },
  { id: "emp-33", branch_id: "branch-newroch", emp_no: "001592", classification: "Groundperson", last_name: "LORENZO OGANDO", first_name: "FRANCISCO", pay_per_hr: 25.0, supplemental_per_hr: 1.67, active: true },
  { id: "emp-34", branch_id: "branch-newroch", emp_no: "001208", classification: "Spray Tech", last_name: "NAJERA", first_name: "OSCAR", pay_per_hr: 32.0, supplemental_per_hr: 5.37, active: true },
  { id: "emp-35", branch_id: "branch-newroch", emp_no: "000061", classification: "Spray Tech", last_name: "IBARRA", first_name: "LEOBARDO", pay_per_hr: 37.0, supplemental_per_hr: 6.8, active: true },
  { id: "emp-36", branch_id: "branch-newroch", emp_no: "000052", classification: "Spray Tech", last_name: "MARTINEZ", first_name: "FEDERICO", pay_per_hr: 35.0, supplemental_per_hr: 3.89, active: true },
  { id: "emp-37", branch_id: "branch-newroch", emp_no: "000062", classification: "Foreman", last_name: "SANCHEZ", first_name: "JOSE MARIA", pay_per_hr: 37.0, supplemental_per_hr: 3.29, active: true },
  { id: "emp-38", branch_id: "branch-newroch", emp_no: "001537", classification: "Spray Tech", last_name: "VIDAL", first_name: "ENRIQUE", pay_per_hr: 25.0, supplemental_per_hr: 1.67, active: true },
  { id: "emp-39", branch_id: "branch-newroch", emp_no: "000115", classification: "Climber", last_name: "RABANELES", first_name: "AURELIO", pay_per_hr: 31.0, supplemental_per_hr: 3.4, active: true },
  { id: "emp-40", branch_id: "branch-newroch", emp_no: "001321", classification: "Groundperson", last_name: "VASQUEZ", first_name: "ERIC", pay_per_hr: 25.0, supplemental_per_hr: 1.67, active: true },
  { id: "emp-41", branch_id: "branch-newroch", emp_no: "001227", classification: "Foreman", last_name: "ALVAREZ", first_name: "BELISARIO", pay_per_hr: 40.0, supplemental_per_hr: 2.91, active: true },
  { id: "emp-42", branch_id: "branch-newroch", emp_no: "001279", classification: "Groundperson", last_name: "NUNEZ", first_name: "EDY", pay_per_hr: 24.0, supplemental_per_hr: 1.68, active: true },
  { id: "emp-43", branch_id: "branch-newroch", emp_no: "001291", classification: "Groundperson", last_name: "ROSA ALMAZAN", first_name: "VICTOR", pay_per_hr: 17.0, supplemental_per_hr: 1.41, active: true },
  { id: "emp-44", branch_id: "branch-newroch", emp_no: "001294", classification: "Foreman", last_name: "FLORES", first_name: "JAMIE", pay_per_hr: 30.0, supplemental_per_hr: 4.21, active: true },
  { id: "emp-45", branch_id: "branch-newroch", emp_no: "000057", classification: "Nursery- Field", last_name: "CRUZ LOYOLA", first_name: "JULIO", pay_per_hr: 24.0, supplemental_per_hr: 1.07, active: true },
  { id: "emp-46", branch_id: "branch-newroch", emp_no: "000055", classification: "Nursery- Field", last_name: "CRUZ LOYOLA", first_name: "CHARLI", pay_per_hr: 24.0, supplemental_per_hr: 1.49, active: true },
  { id: "emp-47", branch_id: "branch-newroch", emp_no: "000110", classification: "Nursery- Mulch Yard", last_name: "QUIJANO", first_name: "RICHARD", pay_per_hr: 25.0, supplemental_per_hr: 1.67, active: true },
  { id: "emp-48", branch_id: "branch-newroch", emp_no: "000109", classification: "Nursery- Driver", last_name: "PIPPO", first_name: "ROSSANO", pay_per_hr: 30.0, supplemental_per_hr: 2.67, active: true },
  { id: "emp-49", branch_id: "branch-stamford", emp_no: "001377", classification: "Climber", last_name: "CAMEY", first_name: "HUMBERTO", pay_per_hr: 28.0, supplemental_per_hr: 2.01, active: true },
  { id: "emp-50", branch_id: "branch-stamford", emp_no: "000089", classification: "Spray Tech", last_name: "CHRISTOFORO", first_name: "MARK", pay_per_hr: 34.0, supplemental_per_hr: 8.19, active: true },
  { id: "emp-51", branch_id: "branch-stamford", emp_no: "001497", classification: "Climber", last_name: "BONILLA", first_name: "ALBERTH", pay_per_hr: 29.0, supplemental_per_hr: 1.75, active: true },
  { id: "emp-52", branch_id: "branch-stamford", emp_no: "001440", classification: "Lawn Tech", last_name: "JAGNARINE", first_name: "RAMLALL", pay_per_hr: 34.0, supplemental_per_hr: 4.24, active: true },
  { id: "emp-53", branch_id: "branch-stamford", emp_no: "000093", classification: "Lawn Tech", last_name: "FINNEY", first_name: "MICHAEL", pay_per_hr: 36.0, supplemental_per_hr: 5.97, active: true },
  { id: "emp-54", branch_id: "branch-stamford", emp_no: "000109", classification: "Climber", last_name: "LOPEZ", first_name: "ENDER", pay_per_hr: 36.0, supplemental_per_hr: 4.54, active: true },
  { id: "emp-55", branch_id: "branch-stamford", emp_no: "000057", classification: "Foreman", last_name: "PEREZ", first_name: "MIGUEL", pay_per_hr: 41.0, supplemental_per_hr: 8.14, active: true },
  { id: "emp-56", branch_id: "branch-stamford", emp_no: "001319", classification: "Foreman", last_name: "LAINEZ", first_name: "HERNAN", pay_per_hr: 35.0, supplemental_per_hr: 5.23, active: true },
  { id: "emp-57", branch_id: "branch-stamford", emp_no: "001241", classification: "Foreman", last_name: "HUERTAS LOPEZ", first_name: "JORGE", pay_per_hr: 37.0, supplemental_per_hr: 2.66, active: true },
  { id: "emp-58", branch_id: "branch-stamford", emp_no: "001415", classification: "Foreman", last_name: "LARA", first_name: "VICTOR", pay_per_hr: 37.0, supplemental_per_hr: 3.29, active: true },
  { id: "emp-59", branch_id: "branch-stamford", emp_no: "001390", classification: "Climber", last_name: "LARA ZUNIGA", first_name: "JHONSON", pay_per_hr: 28.0, supplemental_per_hr: 2.2, active: true },
  { id: "emp-60", branch_id: "branch-stamford", emp_no: "001543", classification: "Groundperson", last_name: "ORTEZ RAMIREZ", first_name: "LESTER", pay_per_hr: 24.0, supplemental_per_hr: 1.6, active: true },
  { id: "emp-61", branch_id: "branch-stamford", emp_no: "001513", classification: "Groundperson", last_name: "OLIVARES", first_name: "LUIS", pay_per_hr: 22.0, supplemental_per_hr: 1.47, active: true },
  { id: "emp-62", branch_id: "branch-stamford", emp_no: "001418", classification: "Climber", last_name: "ORTEGA", first_name: "SERGIO", pay_per_hr: 27.0, supplemental_per_hr: 1.8, active: true },
  { id: "emp-63", branch_id: "branch-stamford", emp_no: "001567", classification: "Groundperson", last_name: "PEREZ A", first_name: "MIGUEL", pay_per_hr: 23.0, supplemental_per_hr: 1.53, active: true },
  { id: "emp-64", branch_id: "branch-stamford", emp_no: "001568", classification: "Spray Tech", last_name: "SANTACRUZ", first_name: "OSCAR", pay_per_hr: 32.0, supplemental_per_hr: 2.13, active: true },
  { id: "emp-65", branch_id: "branch-stamford", emp_no: "000074", classification: "Climber", last_name: "SANTIAGO", first_name: "GERARDO", pay_per_hr: 29.0, supplemental_per_hr: 3.01, active: true },
  { id: "emp-66", branch_id: "branch-haledon", emp_no: "000065", classification: "Foreman", last_name: "CORONA", first_name: "AMADOR", pay_per_hr: 34.5, supplemental_per_hr: 3.48, active: true },
  { id: "emp-67", branch_id: "branch-haledon", emp_no: "001465", classification: "Groundperson", last_name: "ANGUIANO", first_name: "IVAN", pay_per_hr: 24.0, supplemental_per_hr: 1.67, active: true },
  { id: "emp-68", branch_id: "branch-haledon", emp_no: "001540", classification: "Groundperson", last_name: "CABALLERO", first_name: "JULIETA", pay_per_hr: 21.0, supplemental_per_hr: 1.4, active: true },
  { id: "emp-69", branch_id: "branch-haledon", emp_no: "001576", classification: "Lawn Tech", last_name: "JEAN BAPTISTE", first_name: "LOVENS", pay_per_hr: 28.0, supplemental_per_hr: 1.87, active: true },
  { id: "emp-70", branch_id: "branch-haledon", emp_no: "000101", classification: "Spray Tech", last_name: "HURLEY", first_name: "JAMES", pay_per_hr: 35.0, supplemental_per_hr: 3.11, active: true },
  { id: "emp-71", branch_id: "branch-haledon", emp_no: "000071", classification: "Foreman", last_name: "ANGUIANO", first_name: "SERGIO", pay_per_hr: 40.0, supplemental_per_hr: 5.88, active: true },
  { id: "emp-72", branch_id: "branch-haledon", emp_no: "001569", classification: "Climber", last_name: "LLERA", first_name: "SIMON", pay_per_hr: 30.0, supplemental_per_hr: 2.0, active: true },
  { id: "emp-73", branch_id: "branch-haledon", emp_no: "000060", classification: "Climber", last_name: "OLIVERA", first_name: "JOSE", pay_per_hr: 32.0, supplemental_per_hr: 2.67, active: true },
  { id: "emp-74", branch_id: "branch-haledon", emp_no: "000166", classification: "Groundperson", last_name: "ROSAS", first_name: "CARLOS", pay_per_hr: 23.0, supplemental_per_hr: 1.79, active: true },
];

export const SEED_EQUIPMENT: EquipmentRow[] = [
  { id: "eq-0", truck_number: "40", equipment_name: "Tractor", fuel_gph: 4.5, annual_maint: 21621.38, annual_lic: 1327.25, days_used_per_year: 220, active: true },
  { id: "eq-1", truck_number: "48", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 7890.78, annual_lic: 280.5, days_used_per_year: 220, active: true },
  { id: "eq-2", truck_number: "60", equipment_name: "Roll Off", fuel_gph: 3.5, annual_maint: 18132.53, annual_lic: 414.5, days_used_per_year: 220, active: true },
  { id: "eq-3", truck_number: "62", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 10509.28, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-4", truck_number: "64", equipment_name: "75' Bucket", fuel_gph: 4.0, annual_maint: 17414.88, annual_lic: 511.0, days_used_per_year: 220, active: true },
  { id: "eq-5", truck_number: "65", equipment_name: "75' Bucket", fuel_gph: 4.0, annual_maint: 8814.05, annual_lic: 599.1, days_used_per_year: 220, active: true },
  { id: "eq-6", truck_number: "68", equipment_name: "Grapple", fuel_gph: 3.5, annual_maint: 12498.88, annual_lic: 599.1, days_used_per_year: 220, active: true },
  { id: "eq-7", truck_number: "83", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 10000.0, annual_lic: 409.5, days_used_per_year: 220, active: true },
  { id: "eq-8", truck_number: "84", equipment_name: "56' Bucket", fuel_gph: 3.5, annual_maint: 7300.62, annual_lic: 325.25, days_used_per_year: 220, active: true },
  { id: "eq-9", truck_number: "85", equipment_name: "56' Bucket", fuel_gph: 3.5, annual_maint: 513.4, annual_lic: 599.1, days_used_per_year: 220, active: true },
  { id: "eq-10", truck_number: "87", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 2055.01, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-11", truck_number: "88", equipment_name: "56' Bucket", fuel_gph: 3.5, annual_maint: 4527.52, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-12", truck_number: "90", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 8099.9, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-13", truck_number: "91", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 9413.57, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-14", truck_number: "92", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 9000.0, annual_lic: 247.0, days_used_per_year: 220, active: true },
  { id: "eq-15", truck_number: "93", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 9000.0, annual_lic: 322.5, days_used_per_year: 220, active: true },
  { id: "eq-16", truck_number: "94", equipment_name: "Sprinter Van", fuel_gph: 1.0, annual_maint: 2738.49, annual_lic: 116.5, days_used_per_year: 220, active: true },
  { id: "eq-17", truck_number: "95", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 5180.46, annual_lic: 164.2, days_used_per_year: 220, active: true },
  { id: "eq-18", truck_number: "96", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 12362.48, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-19", truck_number: "97", equipment_name: "75' Bucket", fuel_gph: 4.0, annual_maint: 22679.98, annual_lic: 325.25, days_used_per_year: 220, active: true },
  { id: "eq-20", truck_number: "98", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 8393.57, annual_lic: 409.5, days_used_per_year: 220, active: true },
  { id: "eq-21", truck_number: "99", equipment_name: "Grapple", fuel_gph: 3.5, annual_maint: 13962.44, annual_lic: 325.25, days_used_per_year: 220, active: true },
  { id: "eq-22", truck_number: "100", equipment_name: "56' Bucket", fuel_gph: 3.5, annual_maint: 13367.3, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-23", truck_number: "101", equipment_name: "56' Bucket", fuel_gph: 3.5, annual_maint: 21025.89, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-24", truck_number: "102", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 7212.4, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-25", truck_number: "103", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 4732.72, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-26", truck_number: "104", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 8087.12, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-27", truck_number: "105", equipment_name: "Mason Dump", fuel_gph: 2.5, annual_maint: 9001.81, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-28", truck_number: "106", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 7445.96, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-29", truck_number: "107", equipment_name: "Mason Dump", fuel_gph: 2.5, annual_maint: 8087.77, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-30", truck_number: "108", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 5958.63, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-31", truck_number: "109", equipment_name: "Hook Lift", fuel_gph: 3.0, annual_maint: 9000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-32", truck_number: "109", equipment_name: "Mini Rolloff Chip Dump", fuel_gph: 2.8, annual_maint: 7706.11, annual_lic: 322.5, days_used_per_year: 220, active: true },
  { id: "eq-33", truck_number: "109", equipment_name: "Mini Rolloff Chipper Box", fuel_gph: 2.5, annual_maint: 750.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-34", truck_number: "109", equipment_name: "Mini Rolloff Container", fuel_gph: 0, annual_maint: 500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-35", truck_number: "110", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 4769.8, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-36", truck_number: "111", equipment_name: "75' Bucket", fuel_gph: 4.0, annual_maint: 15833.03, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-37", truck_number: "112", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 6075.77, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-38", truck_number: "113", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 7431.79, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-39", truck_number: "114", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 6428.71, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-40", truck_number: "115", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 8538.01, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-41", truck_number: "116", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 3891.47, annual_lic: 247.0, days_used_per_year: 220, active: true },
  { id: "eq-42", truck_number: "117", equipment_name: "Mason Dump", fuel_gph: 2.5, annual_maint: 4724.06, annual_lic: 247.0, days_used_per_year: 220, active: true },
  { id: "eq-43", truck_number: "118", equipment_name: "Mason Dump", fuel_gph: 2.5, annual_maint: 7597.37, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-44", truck_number: "120", equipment_name: "75' Bucket", fuel_gph: 4.0, annual_maint: 20835.64, annual_lic: 599.1, days_used_per_year: 220, active: true },
  { id: "eq-45", truck_number: "121", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 12112.89, annual_lic: 325.25, days_used_per_year: 220, active: true },
  { id: "eq-46", truck_number: "122", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 5599.78, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-47", truck_number: "123", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 7917.3, annual_lic: 409.5, days_used_per_year: 220, active: true },
  { id: "eq-48", truck_number: "124", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 2747.1, annual_lic: 224.0, days_used_per_year: 220, active: true },
  { id: "eq-49", truck_number: "125", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 6310.04, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-50", truck_number: "126", equipment_name: "Hook Lift", fuel_gph: 3.0, annual_maint: 13772.98, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-51", truck_number: "127", equipment_name: "Grapple", fuel_gph: 3.5, annual_maint: 10525.69, annual_lic: 325.25, days_used_per_year: 220, active: true },
  { id: "eq-52", truck_number: "128", equipment_name: "Hook Lift", fuel_gph: 3.0, annual_maint: 5450.38, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-53", truck_number: "129", equipment_name: "Hook Lift", fuel_gph: 3.0, annual_maint: 2695.98, annual_lic: 409.5, days_used_per_year: 220, active: true },
  { id: "eq-54", truck_number: "130", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 3554.6, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-55", truck_number: "131", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 2287.15, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-56", truck_number: "132", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 2868.24, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-57", truck_number: "133", equipment_name: "Mason Dump", fuel_gph: 2.5, annual_maint: 6434.25, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-58", truck_number: "134", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 1709.34, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-59", truck_number: "135", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 1733.52, annual_lic: 384.2, days_used_per_year: 220, active: true },
  { id: "eq-60", truck_number: "136", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 4724.56, annual_lic: 409.5, days_used_per_year: 220, active: true },
  { id: "eq-61", truck_number: "137", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 3974.52, annual_lic: 247.0, days_used_per_year: 220, active: true },
  { id: "eq-62", truck_number: "138", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 2189.04, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-63", truck_number: "139", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 7994.45, annual_lic: 373.75, days_used_per_year: 220, active: true },
  { id: "eq-64", truck_number: "140", equipment_name: "60' Bucket", fuel_gph: 3.5, annual_maint: 2843.0, annual_lic: 325.25, days_used_per_year: 220, active: true },
  { id: "eq-65", truck_number: "141", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 323.53, annual_lic: 409.5, days_used_per_year: 220, active: true },
  { id: "eq-66", truck_number: "142", equipment_name: "Chip Dump", fuel_gph: 2.8, annual_maint: 3586.39, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-67", truck_number: "143", equipment_name: "Grapple", fuel_gph: 3.5, annual_maint: 7334.64, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-68", truck_number: "144", equipment_name: "Grapple", fuel_gph: 3.5, annual_maint: 6806.97, annual_lic: 273.25, days_used_per_year: 220, active: true },
  { id: "eq-69", truck_number: "145", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 1391.71, annual_lic: 189.0, days_used_per_year: 220, active: true },
  { id: "eq-70", truck_number: "146", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 2504.16, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-71", truck_number: "147", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 5996.9, annual_lic: 322.5, days_used_per_year: 220, active: true },
  { id: "eq-72", truck_number: "148", equipment_name: "75' Bucket", fuel_gph: 4.0, annual_maint: 1504.53, annual_lic: 280.75, days_used_per_year: 220, active: true },
  { id: "eq-73", truck_number: "149", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 936.87, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-74", truck_number: "150", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 514.94, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-75", truck_number: "151", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 538.45, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-76", truck_number: "152", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 1049.15, annual_lic: 247.0, days_used_per_year: 220, active: true },
  { id: "eq-77", truck_number: "153", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 618.33, annual_lic: 322.5, days_used_per_year: 220, active: true },
  { id: "eq-78", truck_number: "154", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 1039.66, annual_lic: 425.0, days_used_per_year: 220, active: true },
  { id: "eq-79", truck_number: "155", equipment_name: "PHC Truck", fuel_gph: 2.3, annual_maint: 174.15, annual_lic: 425.0, days_used_per_year: 220, active: true },
  { id: "eq-80", truck_number: "156", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 279.95, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-81", truck_number: "157", equipment_name: "Lawn Truck", fuel_gph: 1.8, annual_maint: 335.69, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-82", truck_number: "158", equipment_name: "Container", fuel_gph: 0, annual_maint: 500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-83", truck_number: "158", equipment_name: "Switch & Go", fuel_gph: 3.0, annual_maint: 477.7, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-84", truck_number: "159", equipment_name: "Container", fuel_gph: 0, annual_maint: 500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-85", truck_number: "159", equipment_name: "Switch & Go", fuel_gph: 3.0, annual_maint: 882.04, annual_lic: 247.0, days_used_per_year: 220, active: true },
  { id: "eq-86", truck_number: "160", equipment_name: "70' Bucket w/Elevator", fuel_gph: 4.0, annual_maint: 12000.0, annual_lic: 1100.0, days_used_per_year: 220, active: true },
  { id: "eq-87", truck_number: "161", equipment_name: "70' Bucket w/Elevator", fuel_gph: 4.0, annual_maint: 12000.0, annual_lic: 1100.0, days_used_per_year: 220, active: true },
  { id: "eq-88", truck_number: "206", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 7585.84, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-89", truck_number: "207", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 2665.48, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-90", truck_number: "209", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 4634.4, annual_lic: 10.0, days_used_per_year: 220, active: true },
  { id: "eq-91", truck_number: "210", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 1222.71, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-92", truck_number: "211", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 745.34, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-93", truck_number: "212", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 806.52, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-94", truck_number: "213", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 1628.86, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-95", truck_number: "214", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 888.75, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-96", truck_number: "215", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 797.49, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-97", truck_number: "216", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 613.29, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-98", truck_number: "217", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 71.05, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-99", truck_number: "218", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 325.9, annual_lic: 27.0, days_used_per_year: 220, active: true },
  { id: "eq-100", truck_number: "219", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 735.01, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-101", truck_number: "221", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-102", truck_number: "222", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-103", truck_number: "226", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-104", truck_number: "227", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 500.64, annual_lic: 107.75, days_used_per_year: 220, active: true },
  { id: "eq-105", truck_number: "228", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 573.87, annual_lic: 91.5, days_used_per_year: 220, active: true },
  { id: "eq-106", truck_number: "229", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-107", truck_number: "230", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 225.33, annual_lic: 126.0, days_used_per_year: 220, active: true },
  { id: "eq-108", truck_number: "231", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1185.0, annual_lic: 48.75, days_used_per_year: 220, active: true },
  { id: "eq-109", truck_number: "232", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 161.33, annual_lic: 91.5, days_used_per_year: 220, active: true },
  { id: "eq-110", truck_number: "233", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 7529.3, annual_lic: 85.5, days_used_per_year: 220, active: true },
  { id: "eq-111", truck_number: "234", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 9.67, annual_lic: 75.5, days_used_per_year: 220, active: true },
  { id: "eq-112", truck_number: "235", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 459.55, annual_lic: 75.5, days_used_per_year: 220, active: true },
  { id: "eq-113", truck_number: "239", equipment_name: "Wheel Loader", fuel_gph: 3.5, annual_maint: 28598.74, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-114", truck_number: "243", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 478.93, annual_lic: 126.0, days_used_per_year: 220, active: true },
  { id: "eq-115", truck_number: "250", equipment_name: "20\" Chipper", fuel_gph: 3.0, annual_maint: 4526.43, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-116", truck_number: "255", equipment_name: "Rotochopper - 255B 2015", fuel_gph: 7.0, annual_maint: 32766.55, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-117", truck_number: "261", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 277.77, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-118", truck_number: "263", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 2538.58, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-119", truck_number: "263", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-120", truck_number: "265", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 3187.25, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-121", truck_number: "268", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-122", truck_number: "271", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-123", truck_number: "272", equipment_name: "PHC Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 75.5, days_used_per_year: 220, active: true },
  { id: "eq-124", truck_number: "273", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 5024.06, annual_lic: 10.0, days_used_per_year: 220, active: true },
  { id: "eq-125", truck_number: "276", equipment_name: "Air-Spade Trailer", fuel_gph: 0, annual_maint: 875.11, annual_lic: 107.75, days_used_per_year: 220, active: true },
  { id: "eq-126", truck_number: "279", equipment_name: "12\" Chipper", fuel_gph: 1.8, annual_maint: 425.46, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-127", truck_number: "280", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 10967.57, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-128", truck_number: "282", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 7335.24, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-129", truck_number: "283", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 6871.81, annual_lic: 126.0, days_used_per_year: 220, active: true },
  { id: "eq-130", truck_number: "284", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 1317.23, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-131", truck_number: "286", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 6749.19, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-132", truck_number: "288", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 2610.32, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-133", truck_number: "289", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 449.37, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-134", truck_number: "293", equipment_name: "18\" Chipper", fuel_gph: 3.0, annual_maint: 5016.14, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-135", truck_number: "295", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 2510.6, annual_lic: 126.0, days_used_per_year: 220, active: true },
  { id: "eq-136", truck_number: "298", equipment_name: "15\" Chipper", fuel_gph: 2.3, annual_maint: 5006.99, annual_lic: 32.0, days_used_per_year: 220, active: true },
  { id: "eq-137", truck_number: "300", equipment_name: "Skid Steer", fuel_gph: 2.3, annual_maint: 5000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-138", truck_number: "301", equipment_name: "Wheel Loader", fuel_gph: 3.5, annual_maint: 11000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-139", truck_number: "303", equipment_name: "Skid Steer", fuel_gph: 2.3, annual_maint: 486.2, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-140", truck_number: "305", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 4000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-141", truck_number: "306", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 4000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-142", truck_number: "307", equipment_name: "Skid Steer", fuel_gph: 2.3, annual_maint: 5000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-143", truck_number: "308", equipment_name: "Grinder", fuel_gph: 7.0, annual_maint: 12000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-144", truck_number: "311", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 5134.72, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-145", truck_number: "312", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 2717.74, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-146", truck_number: "313", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 3500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-147", truck_number: "314", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 428.14, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-148", truck_number: "315", equipment_name: "Compressor", fuel_gph: 1.8, annual_maint: 2000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-149", truck_number: "316", equipment_name: "Branch Manager", fuel_gph: 2.0, annual_maint: 3500.0, annual_lic: 100.0, days_used_per_year: 220, active: true },
  { id: "eq-150", truck_number: "323", equipment_name: "Pickup Truck", fuel_gph: 1.3, annual_maint: 10863.99, annual_lic: 28.75, days_used_per_year: 220, active: true },
  { id: "eq-151", truck_number: "324", equipment_name: "Shop Service Truck", fuel_gph: 1.5, annual_maint: 7500.05, annual_lic: 360.5, days_used_per_year: 220, active: true },
  { id: "eq-152", truck_number: "325", equipment_name: "Hook Lift", fuel_gph: 3.0, annual_maint: 1271.34, annual_lic: 323.5, days_used_per_year: 220, active: true },
  { id: "eq-153", truck_number: "327", equipment_name: "Pickup Truck", fuel_gph: 1.3, annual_maint: 2366.27, annual_lic: 142.6, days_used_per_year: 220, active: true },
  { id: "eq-154", truck_number: "328", equipment_name: "Pickup Truck", fuel_gph: 1.3, annual_maint: 925.08, annual_lic: 254.0, days_used_per_year: 220, active: true },
  { id: "eq-155", truck_number: "329", equipment_name: "Switch & Go", fuel_gph: 3.0, annual_maint: 784.13, annual_lic: 225.0, days_used_per_year: 220, active: true },
  { id: "eq-156", truck_number: "333", equipment_name: "Fork Lift", fuel_gph: 0.8, annual_maint: 3000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-157", truck_number: "400", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-158", truck_number: "401", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-159", truck_number: "402", equipment_name: "Lawn Machine", fuel_gph: 1.5, annual_maint: 2000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-160", truck_number: "403", equipment_name: "Lawn Aerator", fuel_gph: 0.4, annual_maint: 750.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-161", truck_number: "404", equipment_name: "Spreader", fuel_gph: 1.5, annual_maint: 2000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-162", truck_number: "408", equipment_name: "Spreader", fuel_gph: 1.5, annual_maint: 2000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-163", truck_number: "409", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-164", truck_number: "416", equipment_name: "Riding Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-165", truck_number: "417", equipment_name: "Riding Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-166", truck_number: "418", equipment_name: "Riding Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-167", truck_number: "419", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 135.59, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-168", truck_number: "420", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 9573.97, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-169", truck_number: "421", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-170", truck_number: "422", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-171", truck_number: "423", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-172", truck_number: "425", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-173", truck_number: "426", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-174", truck_number: "429", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-175", truck_number: "430", equipment_name: "Lawn Applicator", fuel_gph: 0.6, annual_maint: 1500.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-176", truck_number: "500", equipment_name: "Slow Grinder", fuel_gph: 6.0, annual_maint: 10000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-177", truck_number: "501", equipment_name: "Roll Off", fuel_gph: 3.5, annual_maint: 3313.99, annual_lic: 414.5, days_used_per_year: 220, active: true },
  { id: "eq-178", truck_number: "502", equipment_name: "Trommel SC", fuel_gph: 2.5, annual_maint: 1894.37, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-179", truck_number: "503", equipment_name: "Payloader", fuel_gph: 3.5, annual_maint: 3174.85, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-180", truck_number: "602", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 6000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-181", truck_number: "604", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 6000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-182", truck_number: "604", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-183", truck_number: "605", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 2618.99, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-184", truck_number: "605", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 417.07, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-185", truck_number: "606", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 3587.58, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-186", truck_number: "607", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 1929.23, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-187", truck_number: "607", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1180.29, annual_lic: 75.5, days_used_per_year: 220, active: true },
  { id: "eq-188", truck_number: "608", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 1419.02, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-189", truck_number: "608", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1103.78, annual_lic: 85.5, days_used_per_year: 220, active: true },
  { id: "eq-190", truck_number: "610", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 5587.52, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-191", truck_number: "611", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 2969.29, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-192", truck_number: "611", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 222.69, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-193", truck_number: "612", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 4000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-194", truck_number: "612", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-195", truck_number: "614", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 4000.0, annual_lic: 150.0, days_used_per_year: 220, active: true },
  { id: "eq-196", truck_number: "615", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 4000.0, annual_lic: 150.0, days_used_per_year: 220, active: true },
  { id: "eq-197", truck_number: "616", equipment_name: "Stump Grinder", fuel_gph: 1.8, annual_maint: 4000.0, annual_lic: 150.0, days_used_per_year: 220, active: true },
  { id: "eq-198", truck_number: "700", equipment_name: "92' Spider Lift", fuel_gph: 1.5, annual_maint: 5014.95, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-199", truck_number: "701", equipment_name: "90' Spider Lift", fuel_gph: 1.5, annual_maint: 5000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-200", truck_number: "701", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 1000.0, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-201", truck_number: "702", equipment_name: "90' Spider Lift", fuel_gph: 1.5, annual_maint: 1392.21, annual_lic: 0, days_used_per_year: 220, active: true },
  { id: "eq-202", truck_number: "702", equipment_name: "Trailer", fuel_gph: 0, annual_maint: 9.22, annual_lic: 0, days_used_per_year: 220, active: true },
];
